version: '3.1'
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jaywon.kim0413
      MYSQL_DATABASE: department_of_environment_kmla
      MYSQL_USER: jaywon.kim0413
      MYSQL_PASSWORD: jaywon.kim0413
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: dep-of-env
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/department_of_environment_kmla
      SPRING_DATASOURCE_USERNAME: jaywon.kim0413
      SPRING_DATASOURCE_PASSWORD: jaywon.kim0413
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
volumes:
  db_data: {}